### ISSUE TITLE
Cygnus keeps refilling itself

### ISSUE THREAD

**Issue by ghost** [KSP-RO/Antares-Cygnus#2]
I edit how much fuel cygnus has onboard so I can make it lighter. However when I click the launch button cygnus refills and when I am on the launch pad the deltav stats are different than from when I was in the VAB.

**Comment by raidernick** [comment]
this has absolutely nothing to do with this mod but the launch clamps refilling the resources. Either disable the fuel pumps in the launch clamps or don't use them at all.
